### ISSUE TITLE
Provide better Error Handling when credential class isn't provided.

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-plugin-nornir#56]
### Environment
* Python version:  3.7
* Nautobot version:  1.2.5
* nautobot-plugin-nornir version:  Current

### Steps to Reproduce
1. Install plugin and define plugin configuration without a `credentials` class setting.
```
PLUGINS_CONFIG = {
    "nautobot_plugin_nornir": {
        "dispatcher_mapping": None,
        "username": "cool_user",
        "password": "supersecret",
        "secret": "supersecret",
        "nornir_settings": {
            #"credentials": "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars",
            "runner": {
                "plugin": "threaded",
                "options": {
                    "num_workers": 20,
                },
            },
        },
    },
.....
}
```

### Expected Behavior
If a setting is required like `credential` fail sanely.

### Observed Behavior
Traceback with limited information on how to fix the problem.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nautobot/extras/jobs.py", line 1041, in _run_job
    output = job.run(data=data, commit=commit)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_golden_config/jobs.py", line 48, in inner
    return method(obj, data, commit)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_golden_config/jobs.py", line 103, in run
    config_compliance(self, data)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_golden_config/nornir_plays/config_compliance.py", line 142, in config_compliance
    with InitNornir(
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nornir/init_nornir.py", line 72, in InitNornir
    inventory=load_inventory(config),
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nornir/init_nornir.py", line 20, in load_inventory
    inv = inventory_plugin(**config.inventory.options).load()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_plugin_nornir/plugins/inventory/nautobot_orm.py", line 89, in __init__
    self.cred_class = import_string(credentials_class)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 13, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by JulioPDX** [comment]
Hi @jeffkala facing a similar issue with my install. Any idea on a fix or workaround?

**Comment by jeffkala** [comment]
@JulioPDX , this isn't really a issue necessarily.  It happens when the `credentials` class path isn't provided.  This issue is to clean up the exception handling more than anything.

For the actual fix, make sure your class path is defined in your plugin_config.  There are 3 options.
```
"nornir_settings": {
            "credentials": "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars",
            # or
             "credentials": "nautobot_plugin_nornir.plugins.credentials.settings_vars.CredentialsSettingsVars",
             # or
             "credentials": "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars",
             . . .
```
More info on the differences is here:
https://github.com/nautobot/nautobot-plugin-nornir#:~:text=Out%20of%20the%20box%2C%20users%20have%20access%20to%20three%20classes%3A

**Comment by JulioPDX** [comment]
Worked like a dream. Thank you @jeffkala
